### PR TITLE
try exposing a seemingly platform-dependent bug in example scripts

### PR DESCRIPTION
**Pull request by neutrinoceros**

### CODE REVIEW

**Comment by neutrinoceros** [comment]
Looks like it's on the right track to time out on macOS _and_ windows, while Ubuntu is surviving the issue, as expected from what @vandalt reported in #54.
There's something _really_ wrong going on here.

**Comment by vandalt** [comment]
I was able to see the test output while it was running on MacOS (now I cannot see it anymore). There was some warning about OpenGL (I think?) saying "This could be slow" showed up at the end of calibration/beginning of analysis.

**Comment by neutrinoceros** [comment]
merge #72 to see if it will indeed fix the issue

**Comment by neutrinoceros** [comment]
rotten, closing

**Pull request closed without merging**
