### PR TITLE
BUG: revert a temporary hack (PR 45) designed to improve compat with old versions of astropy

### LINKED ISSUE #31: Astropy commentary cards not handled by munch
When reading a fits file that has `_HeaderCommentaryCards` keys, munch seems to interpret them as mappings and looks for a `.keys`. This causes `amical.extract_bs` to crash with the error message below.

<details>
  <summary>Click to see the error message</summary>
  
```
AttributeError                            Traceback (most recent call last)
<ipython-input-1-a4288c748d4a> in <module>
     99 # Extract raw complex observables for the target and the calibrator:
    100 # It's the core of the pipeline (amical/mf_pipeline/bispect.py)
--> 101 bs_t = amical.extract_bs(cube_t, file_t, targetname=target, **params_ami, display=True)
    102
    103 # %%

~/astro/AMICAL/amical/mf_pipeline/bispect.py in extract_bs(cube, filename, maskname, filtname, t
argetname, instrum, bs_multi_tri, peakmethod, hole_diam, cutoff, fw_splodge, naive_err, n_wl, n_
blocks, theta_detector, scaling_uv, i_wl, unbias_v2, compute_cp_cov, expert_plot, verbose, displ
ay)
   1155         cprint("\nDone (exec time: %d min %2.1f s)." %
   1156                (m, t - m * 60), color="magenta")
-> 1157     return dict2class(obs_result)

~/.pyenv/versions/amical/lib/python3.7/site-packages/munch/__init__.py in munchify(x, factory)
    440         return partial
    441
--> 442     return munchify_cycles(x)
    443
    444

~/.pyenv/versions/amical/lib/python3.7/site-packages/munch/__init__.py in munchify_cycles(obj)
    412         seen[id(obj)] = partial = pre_munchify(obj)
    413         # Then finish munchifying lists and dicts inside obj (reusing munchified obj if
cycles are encountered)
--> 414         return post_munchify(partial, obj)
    415
    416     def pre_munchify(obj):

~/.pyenv/versions/amical/lib/python3.7/site-packages/munch/__init__.py in post_munchify(partial,
 obj)
    431         # might be involved in a cycle
    432         if isinstance(obj, Mapping):
--> 433             partial.update((k, munchify_cycles(obj[k])) for k in iterkeys(obj))
    434         elif isinstance(obj, list):
    435             partial.extend(munchify_cycles(item) for item in obj)

~/.pyenv/versions/amical/lib/python3.7/site-packages/munch/__init__.py in update(self, *args, **
kwargs)
    232         be defined in subclasses.
    233         """
--> 234         for k, v in iteritems(dict(*args, **kwargs)):
    235             self[k] = v
    236

~/.pyenv/versions/amical/lib/python3.7/site-packages/munch/__init__.py in <genexpr>(.0)
    431         # might be involved in a cycle
    432         if isinstance(obj, Mapping):
--> 433             partial.update((k, munchify_cycles(obj[k])) for k in iterkeys(obj))
    434         elif isinstance(obj, list):
    435             partial.extend(munchify_cycles(item) for item in obj)

~/.pyenv/versions/amical/lib/python3.7/site-packages/munch/__init__.py in munchify_cycles(obj)
    412         seen[id(obj)] = partial = pre_munchify(obj)
    413         # Then finish munchifying lists and dicts inside obj (reusing munchified obj if
cycles are encountered)
--> 414         return post_munchify(partial, obj)
    415
    416     def pre_munchify(obj):

~/.pyenv/versions/amical/lib/python3.7/site-packages/munch/__init__.py in post_munchify(partial,
 obj)
    431         # might be involved in a cycle
    432         if isinstance(obj, Mapping):
--> 433             partial.update((k, munchify_cycles(obj[k])) for k in iterkeys(obj))
    434         elif isinstance(obj, list):
    435             partial.extend(munchify_cycles(item) for item in obj)

~/.pyenv/versions/amical/lib/python3.7/site-packages/munch/__init__.py in update(self, *args, **
kwargs)
    232         be defined in subclasses.
    233         """
--> 234         for k, v in iteritems(dict(*args, **kwargs)):
    235             self[k] = v
    236

~/.pyenv/versions/amical/lib/python3.7/site-packages/munch/__init__.py in <genexpr>(.0)
    431         # might be involved in a cycle
    432         if isinstance(obj, Mapping):
--> 433             partial.update((k, munchify_cycles(obj[k])) for k in iterkeys(obj))
    434         elif isinstance(obj, list):
    435             partial.extend(munchify_cycles(item) for item in obj)

~/.pyenv/versions/amical/lib/python3.7/site-packages/munch/__init__.py in munchify_cycles(obj)
    412         seen[id(obj)] = partial = pre_munchify(obj)
    413         # Then finish munchifying lists and dicts inside obj (reusing munchified obj if
cycles are encountered)
--> 414         return post_munchify(partial, obj)
    415
    416     def pre_munchify(obj):

~/.pyenv/versions/amical/lib/python3.7/site-packages/munch/__init__.py in post_munchify(partial,
 obj)
    431         # might be involved in a cycle
    432         if isinstance(obj, Mapping):
--> 433             partial.update((k, munchify_cycles(obj[k])) for k in iterkeys(obj))
    434         elif isinstance(obj, list):
    435             partial.extend(munchify_cycles(item) for item in obj)

~/.pyenv/versions/amical/lib/python3.7/site-packages/munch/__init__.py in update(self, *args, **
kwargs)
    232         be defined in subclasses.
    233         """
--> 234         for k, v in iteritems(dict(*args, **kwargs)):
    235             self[k] = v
    236

~/.pyenv/versions/amical/lib/python3.7/site-packages/munch/__init__.py in <genexpr>(.0)
    431         # might be involved in a cycle
    432         if isinstance(obj, Mapping):
--> 433             partial.update((k, munchify_cycles(obj[k])) for k in iterkeys(obj))
    434         elif isinstance(obj, list):
    435             partial.extend(munchify_cycles(item) for item in obj)

~/.pyenv/versions/amical/lib/python3.7/site-packages/munch/__init__.py in munchify_cycles(obj)
    412         seen[id(obj)] = partial = pre_munchify(obj)
    413         # Then finish munchifying lists and dicts inside obj (reusing munchified obj if
cycles are encountered)
--> 414         return post_munchify(partial, obj)
    415
    416     def pre_munchify(obj):

~/.pyenv/versions/amical/lib/python3.7/site-packages/munch/__init__.py in post_munchify(partial,
 obj)
    431         # might be involved in a cycle
    432         if isinstance(obj, Mapping):
--> 433             partial.update((k, munchify_cycles(obj[k])) for k in iterkeys(obj))
    434         elif isinstance(obj, list):
    435             partial.extend(munchify_cycles(item) for item in obj)

~/.pyenv/versions/amical/lib/python3.7/site-packages/six.py in iterkeys(d, **kw)
    597 if PY3:
    598     def iterkeys(d, **kw):
--> 599         return iter(d.keys(**kw))
    600
    601     def itervalues(d, **kw):

AttributeError: '_HeaderCommentaryCards' object has no attribute 'keys'
```
</details>

Maybe this is an issue with how the `_HeaderCommentaryCards` class is defined in astropy (see [here](https://github.com/astropy/astropy/blob/main/astropy/io/fits/header.py#L2143)) ? The solution could be to file an issue upstream with astropy to see if this could be handled there. Otherwise, this could be handled by AMICAL if you are OK with simply removing the COMMENT and HISTORY keys when creating the oifits files. I implemented the latter fix locally and it works fine. There might also be a better solution. I'm not an expert with astropy fits handling or with munch.

Let me know what you think @DrSoulain. I can then either send a PR or fill an issue on the astropy github (or both, if you want to use the PR as a temporary fix).

### PR DESCRIPTION
**Pull request by neutrinoceros**
revert #45
close #31

I don't think this will work (still broken on my machine) even with the latest astropy (4.3.1) released a few weeks back.
We can keep this open as long as needed and rerun the tests whenever seems relevant, but right now I worry that the supposed fix upstream did not have the expected result for AMICAL. @vandalt, any input ?

### CODE REVIEW

**Comment by vandalt** [comment]
I just checked and it seems that while [the PR that fixed the issue](https://github.com/astropy/astropy/pull/11923) was  merged into the main branch, changes have not made it to a release yet. I checked the two latest release tags on their GitHub ([4.0.6](https://github.com/astropy/astropy/blob/fae05f2cf4360512ff7b9838562b6fbcca9d06ae/astropy/io/fits/header.py#L2162) and [4.3.1](https://github.com/astropy/astropy/blob/b17655f0f55f61f4c54fbe2c546a8854ddf1ef19/astropy/io/fits/header.py#L2143)). The latest changes to the `header.py` is from April in both cases and the line that registers `_CardAcessor` is still there in both releases (see links).

Other than that, I have no idea how the Astropy release cycle works, but we will have to wait a bit more it seems.

I could run the tests again the main astropy branch to double check that the upstream changes fix the issues in AMICAL.

**Comment by vandalt** [comment]
I confirm that the tests all pass against astropy's main branch when the hack is removed from AMICAL (on my machine at least).

**Comment by neutrinoceros** [comment]
Oh, could you also check if the tests pass with this PR against astropy's main ?
I suspect we shouldn't actually merge this ever because it would imply that we start _requiring_ astropy 5, and that doesn't seem like a good idea to me for now. But we could simply have a conditional to vary AMICAL's behavior depending on the detected version for astropy. This would allow to migrate out of your "hack" without breaking backwards compatibility sooner than necessary.

**Comment by neutrinoceros** [comment]
Dropping this in favour of #60

**Pull request closed without merging**
